books = [
    {
        "id": 1,
        "title": "The Alchemist",
        "author": "Paulo Coelho",
        "publication": "HarperCollins",
        "price": 399,
    },
    {
        "id": 2,
        "title": "Atomic Habits",
        "author": "James Clear",
        "publication": "Penguin Random House",
        "price": 550,
    },
    {
        "id": 3,
        "title": "Rich Dad Poor Dad",
        "author": "Robert T. Kiyosaki",
        "publication": "Plata Publishing",
        "price": 450,
    },
    {
        "id": 4,
        "title": "Think and Grow Rich",
        "author": "Napoleon Hill",
        "publication": "The Ralston Society",
        "price": 350,
    },
    {
        "id": 5,
        "title": "The Psychology of Money",
        "author": "Morgan Housel",
        "publication": "Harriman House",
        "price": 499,
    },
    {
        "id": 6,
        "title": "Clean Code",
        "author": "Robert C. Martin",
        "publication": "Prentice Hall",
        "price": 999,
    },
    {
        "id": 7,
        "title": "Deep Work",
        "author": "Cal Newport",
        "publication": "Grand Central Publishing",
        "price": 600,
    },
    {
        "id": 8,
        "title": "The Lean Startup",
        "author": "Eric Ries",
        "publication": "Crown Business",
        "price": 650,
    },
    {
        "id": 9,
        "title": "Sapiens",
        "author": "Yuval Noah Harari",
        "publication": "Harvill Secker",
        "price": 799,
    },
    {
        "id": 10,
        "title": "The Pragmatic Programmer",
        "author": "Andrew Hunt & David Thomas",
        "publication": "Addison-Wesley",
        "price": 1200,
    },
]

