"""error resolving

Revision ID: 99fa024776f0
Revises: c472f8fce944
Create Date: 2026-01-01 21:45:49.319993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '99fa024776f0'
down_revision: Union[str, Sequence[str], None] = 'c472f8fce944'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.drop_column('user', 'is_veriied')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_veriied', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('user', 'is_verified')
    # ### end Alembic commands ###
